spring:
  jpa:
    hibernate:
      ddl-auto: none
  server: # http response 에 UTF-8 인코딩을 강제하는 옵션, 인코딩에 관련된 문제에서 안정적인 응답을 보장하기 위해
    servlet:
      encoding:
        force-response: true
  devtools:
    restart:
      enabled: true

  # default redis settings
  ## spring.redis.host=localhost # configuration에 사용할 정보
  ## spring.redis.port=6397 # configuration에 사용할 정보
  ## spring.redis.password=빈 문자열 혹은 redis 서버에 설정한 패스워드 # configuration에 사용할 정보
  ## spring.redis.lettuce.pool.max-active: # pool에 할당될 수 있는 커넥션 최대수(음수로 설정하면 무제한)
  ## spring.redis.lettuce.pool.max-idle: # pool의 "idle" 커넥션 최대수(음수로 설정하면 무제한)
  ## spring.redis.lettuce.pool.min-idle: # pool의 "idle" 커넥션 최소 수 대상
