spring:
  datasource:
    url: jdbc:mariadb://blanca.c8onspz62ykf.ap-northeast-2.rds.amazonaws.com/blanca?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: adminblanca2530!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect